[package]

name = "testp"
version = "0.0.1"
authors = ["Thomas Jespersen <laumann.thomas@gmail.com>"]


[dev-dependencies.compiletest_rs]
path = ".."
features = ["tmp"]

[features]
rustc = ["compiletest_rs/rustc"]
assembly = []
